### ISSUE TITLE
请教大佬几个问题

### ISSUE THREAD

**Issue by dyw770** [soikjk/ASUSROGB360G-RX580-I58400#1]
system time and alarm source 这个bios选项是什么意思呢？还有我把bios更新到和大佬你一样的版本后，启动clover的时间变得很长（启动后到clover的引导界面的时间），不知道大佬你的会不会也这样

**Comment by soikjk** [comment]
主板设置➡Advanced➡Advanced PCH Configuration➡system time and alarm source➡Legacy RTC；你试试这样一设置

**Comment by dyw770** [comment]
就是看了大佬更新的文档后，想问下system time and alarm source这个设置的含义是什么。😢因为我更新bios后出了点问题，window下的声卡都检测不到了。

**Comment by soikjk** [comment]
RTC全程 real time clock 我的主板不这样设置有时会重置cmos 你看看你还改了其他的东西了么 不行的话Bios恢复一下出厂设置 然后再设置一下。如果你的硬件配置和我的一样 直接用 bios配置文件恢复一下设置就行。       windows声卡的话我没用黑苹果之前有时windows有时也没声音…………重启两次有时候就好了。

**Comment by dyw770** [comment]
好的 感谢大佬

**Comment by soikjk** [comment]
忘记说了我显卡设置的是独显优先。这个你注意一下如果你显示器连接的是集显可能没信号

**Comment by dyw770** [comment]
okok😃

**Comment by dyw770** [comment]
很抱歉，再次来打扰大佬你，上次我更新了bios后发现不开启
```
➡Advanced➡Advanced PCH Configuration➡system time and alarm source➡Legacy RTC；
```
这个就不能进系统，后面去搜索一下发现了一个补丁可以解决这个问题。https://www.tonymacx86.com/threads/fix-for-boot-hangs-after-bios-update-acpi-patch.275091/，兵这个补丁貌似可以解决大部分主板因升级bios导致的无法启动问题.
